image:
  tag: 8.5.1
  pullPolicy: IfNotPresent
javaMem: "-Xms1g -Xmx1g"
logLevel: "INFO"
replicaCount: 2
livenessProbe:
  initialDelaySeconds: 420
exporter:
  readinessProbe:
    periodSeconds: 30
zookeeper:
  replicaCount: 1  # Desired quantity of ZooKeeper pods. This should always be (1,3,5, or 7)
