defaultBackend:
  enabled: true
controller:
#  defaultBackendService: "default/studio-studio"
#  hostNetwork: false
#  nodeSelector:
#    dla-role: master
  service:
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: true
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: ssl
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: datalayer-role=studio,kuber-role=studio
#      service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: 60
#      service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: true
#      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us...
#      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
#      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,8443"
#      service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: ""
#      service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: my-logs-bucket
#      service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: logs/prod
#      nginx.ingress.kubernetes.io/ssl-redirect: true
#      nginx.ingress.kubernetes.io/force-ssl-redirect: true
#  tcp:
#   81: default/studio-studio:8080
