apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kuber-svc
  labels:
    app: {{ template "kuber.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.kuber.port }}
    name: kuber-http
  selector:
    app: {{ template "kuber.name" . }}
    release: {{ .Release.Name }}
