{{ if eq .Values.studio.clusterType "eks" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: studio-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    cert-manager.io/acme-challenge-type: 'http01'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
  - hosts:
    - alpha.datalayer.io
    secretName: studio-datalayer-io-cert
  rules:
  - host: alpha.datalayer.io
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-studio-svc
            servicePort: {{ .Values.studio.port }}
{{- end }}
