{{ if eq .Values.studio.clusterType "minikube" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: studio-ingress
  namespace: {{ .Release.Namespace }}
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2
spec:
  rules:
  - host: minikube.datalayer.io.local
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .Release.Name }}-studio-svc
          servicePort: {{ .Values.studio.port }}
{{- end }}
