apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-studio-svc
  labels:
    app: {{ template "studio.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.studio.port }}
    name: studio-http
  selector:
    app: {{ template "studio.name" . }}
    release: {{ .Release.Name }}
