apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  DLA_IAM_AUTH_CALLBACK: {{ .Values.config.DLA_IAM_AUTH_CALLBACK }}
  DLA_STUDIO_INDEX_PAGE: {{ .Values.config.DLA_STUDIO_INDEX_PAGE }}
