#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Redeploying Datalayer DSP on K8S"$NOCOLOR$NOBOLD
echo

CMDS="$2"
IFS=',' read -ra CMD_SPLITS <<< "$CMDS"

DLA_SKIP_HEADER=true dla dsp-down $CMD_SPLITS
echo ...
echo
# sleep 5s

DLA_SKIP_HEADER=true dla dsp-up "$@"
