#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Installing Apache Hadoop"$NOCOLOR$NOBOLD
echo

rm -fr $DLAOPT/hadoop* || true

cd $DLAOPT && \
  curl https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz | tar -xz && \
  ln -s hadoop-${HADOOP_VERSION} hadoop
