#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Datalayer HBase Status"$NOCOLOR$NOBOLD
echo

python <<EOF
import happybase
connection = happybase.Connection('0.0.0.0')
print('TABLES')
for table in connection.tables():
    print(table)
EOF
