#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Starting Apache HDFS..."$NOCOLOR$NOBOLD
echo

export DLA_HADOOP_STATUS=starting

# $HADOOP_HOME/sbin/start-dfs.sh 

# To debug Kerberos, use -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true -Djavax.net.debug=all

# Start the HDFS with the following command, run on the designated NameNode.
echo -e $BOLD$GREEN"Starting HDFS Namenode..."$NOCOLOR$NOBOLD
$HADOOP_HOME/bin/hdfs --daemon start namenode

# Start the Secondary NameNode.
echo -e $BOLD$GREEN"Starting HDFS Secondary Namenode..."$NOCOLOR$NOBOLD
$HADOOP_HOME/bin/hdfs --daemon start secondarynamenode

# Run a script to start DataNodes on all slaves.
echo -e $BOLD$GREEN"Starting HDFS Datanode..."$NOCOLOR$NOBOLD
$HADOOP_HOME/bin/hdfs --daemon start datanode

DLA_SKIP_HEADER=true dla hdfs-help
