#!/usr/bin/env bash

# Copyright (c) Datalayer https://datalayer.io
# Distributed under the terms of the Apache License, Version 2.0
# https://www.apache.org/licenses/LICENSE-2.0.txt

echo -e $BOLD$YELLOW"Installing Apache Solr"$NOCOLOR$NOBOLD
echo

rm -fr $DLAOPT/solr* || true

cd $DLAOPT && \
  curl https://downloads.apache.org/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz | tar -xz && \
  ln -s solr-${SOLR_VERSION} solr
