{{ if .Values.simple.ingress -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: '/'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    cert-manager.io/acme-challenge-type: 'http01'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
  - hosts:
    - simple.datalayer.io
    secretName: simple-datalayer-io-cert
  rules:
  - host: simple.datalayer.io
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Values.service.name }}
            servicePort: 8080
{{- end }}
