{{ if eq .Values.library.clusterType "eks" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: library-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    cert-manager.io/acme-challenge-type: 'http01'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
  - hosts:
    - alpha.datalayer.io
    secretName: library-datalayer-io-cert
  rules:
  - host: alpha.datalayer.io
    http:
      paths:
        - path: /api/library
          backend:
            serviceName:  {{ .Release.Name }}-library-svc
            servicePort: 9800
{{- end }}
