{{ if eq .Values.library.clusterType "minikube" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: library-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$3
spec:
  rules:
  - host: minikube.datalayer.io.local
    http:
      paths:
      - path: /api/(library)(/|$)(.*)
        backend:
          serviceName: {{ .Release.Name }}-library-svc
          servicePort: {{ .Values.library.port }}
{{- end }}
