{{ if eq .Values.iam.clusterType "minikube" -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: iam-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$3
spec:
  rules:
  - host: minikube.datalayer.io.local
    http:
      paths:
      - path: /api/(iam)(/|$)(.*)
        backend:
          serviceName: {{ .Release.Name }}-iam-svc
          servicePort: {{ .Values.iam.port }}
{{- end }}
